import gdb
import struct
import sys
import os

sys.path.append(os.getcwd())
from CodeStackHelpers import *
from SymbTableHelpers import *

	
def PrintCurrTokens(amount):
	PrintTokens(GetCurrParserStackPtr(), amount)
	
def PrintToken(tok, param, offset, index=None, is_current=False):
	global TokenNames
	offsetStr = '0x%06x' % (offset & 0xFFFFFFFF)

	if is_current:
		prefix = " => "
	else:
		prefix = "    "
	
	if param is None:
		try:
			print(offsetStr + prefix + TokenNames[tok])
		except:
			print(offsetStr + prefix + "[UNKNOWN]")
			return False
	else:
		if ParamIsSymbol(tok):
			paramStr = GetSymbTable()[int(param)].name
		elif tok == zPAR_TOK_CALL:
			paramStr = GetSymbTable()[GetFuncIdByOffset(param)].name
		else:
			paramStr = uhex(param)
			
		if index is not None:
			paramStr += "[" + str(index) + "]"
		print(offsetStr + prefix + "{0: <20}".format(TokenNames[tok]) + paramStr)

def PrintTokens(ptr, amount):
	currentPtr = GetCurrParserStackPtr()
	stackBegin = GetParserStackPtr()
	for i in range(amount):
		offset = ptr - stackBegin
		isCurrent = (ptr == currentPtr)
		param = None
		index = None
		token = ReadByte(ptr)
		ptr += 1
		if RequiresParameter(token):
			param = ReadInt(ptr)
			ptr += 4
		if token == zPAR_TOK_PUSH_ARRAYVAR:
			index = ReadByte(ptr)
			ptr += 1
		result = PrintToken(token, param, offset, index, isCurrent)
		# Sometimes the code generated by Ikarus corrupts part of the codestack (which will never be executed). We print [UNKNOWN] and print no further tokens
		if result == False:
			break
			
def PrintTokensOffset(offset, amount):
	PrintTokens(GetParserStackPtr()+offset, amount)
	
def RequiresParameter(tok):
	if (tok == zPAR_TOK_CALL      or tok == zPAR_TOK_CALLEXTERN) \
	or (tok == zPAR_TOK_PUSHINT   or tok == zPAR_TOK_PUSHVAR) \
	or (tok == zPAR_TOK_PUSHINST  or tok == zPAR_TOK_SETINSTANCE) \
	or (tok == zPAR_TOK_JUMP      or tok == zPAR_TOK_JUMPF) \
	or (tok == zPAR_TOK_PUSH_ARRAYVAR):
		return True
	return False
	
def ParamIsSymbol(tok):
	if (tok == zPAR_TOK_SETINSTANCE 		or tok == zPAR_TOK_CALLEXTERN) \
	or (tok == zPAR_TOK_PUSHVAR 	or tok == zPAR_TOK_PUSHINST):
		return True
	return False